### PR TITLE
fix: resolving tags without attribute values causes confusion

### LINKED ISSUE #486: Parsing an attribute without a value can cause code confusion
**Describe the bug**

Something went wrong when I parsed the following code。

```template
<template>
  <view>
    <image lazy />
    <image></image>
  </view>
</template>
```

The above code is parsed into something like this：

```template
<template>
  <view>
    <image lazy="lazy">
    <image/>
  
</image></view></template>
```

**To Reproduce**
https://stackblitz.com/edit/js-xmldom-template-cyojup?file=index.js

**Expected behavior**

```template
<template>
  <view>
    <image lazy="lazy"/>
    <image/>
  </view>
</template>
```

**Runtime & Version:**
xmldom version:  0.8.6
runtime version: 0.8.6
other related software and version:  

**Additional context**

I tried to solve the problem myself, until I changed the code in `@xmldom/xmldom/lib/sax.js` in such a way that it could parse properly。

```diff
case '/':
	switch(s){
	case S_TAG:
		el.setTagName(source.slice(start,p));
	case S_ATTR_END:
	case S_TAG_SPACE:
	case S_TAG_CLOSE:
		s =S_TAG_CLOSE;
		el.closed = true;
	case S_ATTR_NOQUOT_VALUE:
	case S_ATTR:
-	// case S_ATTR_SPACE:
		break;
+	case S_ATTR_SPACE:
+		el.closed = true;
+		break;
	//case S_EQ:
	default:
		throw new Error("attribute invalid close char('/')") // No known test case
	}
	break;
```
Finally, I put up the [pull request](https://github.com/xmldom/xmldom/pull/485/commits/83205ebed1d19ec886274269b90180519c45becd), I don't know whether my solution is right or not, so you can check it when you are free. 
Thanks.

### PR DESCRIPTION
**Pull request by Bulandent**
Closes #486

### CODE REVIEW

**Comment by karfau** [comment]
Since all tests are green it would be great to add your test case to the PR,
so it never breaks again.

Do you want to try it?

**Comment by karfau** [comment]
Awesome.
I needed to revert the lock file you pushed.
And I will take the time within this week to try to understand the change a bit better, before I will land it and publish the next 0.7 and 0.8 release with this fix.
Thx for you contribution and investment.

**Comment by Bulandent** [comment]
> Awesome. I needed to revert the lock file you pushed. And I will take the time within this week to try to understand the change a bit better, before I will land it and publish the next 0.7 and 0.8 release with this fix. Thx for you contribution and investment.

You are welcome. This was my first pr submission for an open source project, and I felt really good about it. 😁

**Comment by karfau** [comment]
I love your solution to the problem.
Will go ahead and land and release.

**Pull request merged**
