### PR TITLE
fix(types): Copy types from DefinitelyTyped

### PR DESCRIPTION
**Pull request by kachkaev**
This PR partially addresses #191 (see https://github.com/xmldom/xmldom/issues/191#issuecomment-902225494 → step 1). The file was copied from [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/f378781417e2964083f492ac85bad985d0f47650/types/xmldom/index.d.ts).

### CODE REVIEW

**Comment by kachkaev** [comment]
Let me check the changes locally before removing the draft status. If anyone spot anything in the meantime, feel free to raise it in the comments 🙂

**Review by karfau — APPROVED** [review]
It's a pitty we are loosing the tests that are present in Definitly typed.
We should add them as before we make any relevant changes.

Besides that: LGTM

**Comment by kachkaev** [comment]
cc @tkqubo, @karfau (you are [mentioned](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/f378781417e2964083f492ac85bad985d0f47650/types/xmldom/index.d.ts#L3-L4) in DefinitelyTyped → index.d.ts) 👋

**Comment by kachkaev** [comment]
Yeah I completely agree on the tests. This fix we are making is quite rough, but it looks justified given the state of urgency 🙂

**Comment by karfau** [comment]
Need to get some sleep now, but will release it soon.

**Pull request merged**
