### PR TITLE
style: Translate/drop non English comments

### PR DESCRIPTION
**Pull request by shunkica**
I always wondered what this said.

### CODE REVIEW

**Review by karfau — COMMENTED** [review]
I already translated it multiple times, but never wanted to mix that change into the PR I was working on...
Did you try to understand if the code surrounding the comment makes sense? Or rather what the comment actually means?

I will check if that branch is covered by any test and if not try to find a sample that triggers it, to understand if it is actually something that we need TODO something about, or if it van just stand as an explanation of the branch.

**Comment by karfau** [comment]
Even though I don't really understand the code in that place, it is covered by tests.
I would prefer to drop the "TODO" part of the comment, unless we know what we need to do here.

While we are at it, can you also translate the other comments that are not in English?

**Comment by shunkica** [comment]
There is only one other non-English comment I could find and it says "忘记闭合" which translates to "forgot to close". Not very helpful :D

**Comment by karfau** [comment]
in that case lets drop that comment

**Review by karfau — APPROVED** [review]

**Pull request merged**
