### PR TITLE
docs: Add security policy

### PR DESCRIPTION
**Pull request by karfau**
Inspired by the following sources:

- https://snyk.io/blog/ten-git-hub-security-best-practices/
- https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md
- https://expressjs.com/en/resources/contributing.html#security-policies-and-procedures
- https://docs.github.com/en/code-security/security-advisories/about-coordinated-disclosure-of-security-vulnerabilities

### CODE REVIEW

**Comment by karfau** [comment]
@brodybits @kethinov @timbru31 I would like to land this PR latest at the end of the month.

Let me know if you spot something that needs a change.

**Comment by timbru31** [comment]
Awesome, thank you. Will read through it this week 👍

**Comment by karfau** [comment]
@timbru31 Did you have a chance to read it? Do you need more time? Should I just land it?

**Comment by karfau** [comment]
Landing this now, since there was no update since nearly a month.

**Pull request merged**
