### PR TITLE
fix: preserve doctype with sysid (#143)

### LINKED ISSUE #143: DOCTYPE SYSTEM identifiers do not appear to be properly parsed
When parsing an XML document that includes a doctype similar to `<!DOCTYPE custom SYSTEM "custom.dtd">` (SYSTEM identifier for a local DTD filename), the system identifier appears to be parsed as ">".  This is causing problems for us in round-trip usage, as parsing and then serializing the document results in corruption of the DOCTYPE.

I plan on creating a pull request with a fix for this issue.

### PR DESCRIPTION
**Pull request by davidmc24**
Fixes #143

### CODE REVIEW

**Comment by brodybits** [comment]
@karfau do you think we want to include this in the upcoming 0.4.0 release?

**Review by karfau — APPROVED** [review]
Very nice! Thx a lot.

**Comment by karfau** [comment]
@brodybits I don't see a reason why we shouldn't :+1:

**Comment by brodybits** [comment]
The one little thing I wonder is if these changes could introduce any more surviving mutants when running Stryker. Unfortunately I have no time to try this now, and I don't think this should be blocking. @karfau it would be great if you can merge this (as a squash commit). Thanks again!

**Comment by davidmc24** [comment]
I'm glad the PR seems to be well received. Thank you for your work maintaining this library.

**Comment by karfau** [comment]
@brodybits I tried to run stryker after applying the patch, and have received 8 new mutants, but my scores differ for every file from the one produced by github actions on master. So not sure what to derive from it. I guess we will see the result when it lands.

**Comment by brodybits** [comment]
> my scores differ for every file from the one produced by github actions on master

Maybe we should investigate which mutations differ in the reports from the command line vs GitHub.

**Pull request merged**
