### PR TITLE
Improve some XML test strings

### LINKED ISSUE #128: Odds & ends from Prettier formatting of test code [PR #123]
@karfau identified quite a few things in review of PR #123 that should be resolved.

### PR DESCRIPTION
**Pull request by brodybits**
resolves #128 (followup to PR #123 - reformat test code using Prettier)

### CODE REVIEW

**Review by karfau — APPROVED** [review]
LGTM
(Even though I'm not aware why this way of concatenating strings is any different from the other way.)

**Comment by brodybits** [comment]
Better alignment. Yeah maybe not really worth it?

**Comment by karfau** [comment]
> Better alignment. Yeah maybe not really worth it?

Did you already handle all of them?
Since you invested the time we can also land it. But I'm not sure we will be able to keep it this way in the future...
Your choice :)

**Comment by karfau** [comment]
Since you didn't land it: Couldn't/Shouldn't we nowadays just use template strings everywhere, consistently?

**Comment by brodybits** [comment]
> Shouldn't we nowadays just use template strings everywhere, consistently?

Makes sense to me, yes.

**Pull request closed without merging**
