### PR TITLE
Restore `vows` test "suite", drop useless proof tests

### LINKED ISSUE #35: test coverage seems to be very limited
`npm test` continues to succeed if I make some non-sense edits in my work area:

```diff
% git diff      
diff --git a/lib/dom-parser.js b/lib/dom-parser.js
index 92937fd..1726488 100644
--- a/lib/dom-parser.js
+++ b/lib/dom-parser.js
@@ -246,6 +246,6 @@ function appendElement (hander,node) {
 var htmlEntity = require('./entities');
 var XMLReader = require('./sax').XMLReader;
 var DOMImplementation = exports.DOMImplementation = require('./dom').DOMImplementation;
-exports.XMLSerializer = require('./dom').XMLSerializer ;
-exports.DOMParser = DOMParser;
+//exports.XMLSerializer = require('./dom').XMLSerializer ;
+//exports.DOMParser = DOMParser;
 //}
diff --git a/lib/dom.js b/lib/dom.js
index 01794c8..5ffcf27 100644
--- a/lib/dom.js
+++ b/lib/dom.js
@@ -1250,7 +1250,7 @@ try{
 }
 
 //if(typeof require == 'function'){
-       exports.Node = Node;
-       exports.DOMImplementation = DOMImplementation;
-       exports.XMLSerializer = XMLSerializer;
+       //exports.Node = Node;
+       //exports.DOMImplementation = DOMImplementation;
+       //exports.XMLSerializer = XMLSerializer;
 //}
```

I think we need to massively improve the test suite before we can do much more cleanup work.

### PR DESCRIPTION
**Pull request by karfau**
fixes #35 

I found that some part of the `test` folder are using [`vows`](https://github.com/vowsjs/vows) for testing.
- Main changes in the test files is for fixing imports and removing "traversal code" that `vows` is able to handle when invoked from the cli. (`test/**/.js` files that don't have the `.vows.js` extension might still contain assertions. We need to digest them and decide whether and how to restore them.)
- To ease filtering I '''renamed''' those files in an extra commit. we should keep the commits when landing so the git history of those files is not lost. (**For reviewing it's also much easier to go commit by commit.**)
 
All the `vows` tests can now be executed via the usual `npm test`.
Tons of test cases where only calls to `console.assert` that logged an "Assertion failed: ...", I converted them into `assert.[equal|isTrue|greater|...]` where possible. When these failed and it made sense, I changed the expectation to the current value.
In case we need to skip a test, the easiest is still to convert it to `console.assert`.

I also drastically reduced the amount of `console.log` in tests, now the only thing that's printing in addition to `vows` is the internal logging of xmldom.

Stryker can be run using `npm start` for now, I thought it's the most convenient solution for now. See below for the report from my first run.

- I think we can add `jest` in a different PR.
- I found that `&nbsp;` is converted to a normal space instead of `\u00a0`, see [comment](#issuecomment-647081281) and commit afterwards that fixes the regression.

### CODE REVIEW

**Comment by karfau** [comment]
The more I look into those restored tests the more doubts I have thet there is a single assertion in them. `vows` is counting something but the only "assertions in those tests that I could find are `console.assert` and there is a lot of there in the output of running `npm run test`.

**Comment by karfau** [comment]
Stryker was super easy to set up! Awesome.
```
$ npm start
 INFO ConfigReader Using stryker.conf.json
 INFO InputFileResolver Found 4 of 45 file(s) to be mutated.
 INFO InitialTestExecutor Starting initial test run. This may take a while.
 INFO InitialTestExecutor Initial test run succeeded. Ran 1 tests in 2 seconds (net 1070 ms, overhead 2 ms).
 INFO MutatorFacade 1994 Mutant(s) generated
 WARN MutantTestMatcher No coverage result found, even though coverageAnalysis is "all". Assuming that all tests cover each mutant. This might have a big impact on the performance.
 INFO SandboxPool Creating 8 test runners (based on CPU count)
[...]
Ran all tests for this mutant.
Ran 0.97 tests per mutant on average.
---------------|---------|----------|-----------|------------|----------|---------|
File           | % score | # killed | # timeout | # survived | # no cov | # error |
---------------|---------|----------|-----------|------------|----------|---------|
All files      |   55.27 |     1042 |        60 |        892 |        0 |       0 |
 dom-parser.js |   66.18 |      132 |         3 |         69 |        0 |       0 |
 dom.js        |   59.85 |      529 |        30 |        375 |        0 |       0 |
 entities.js   |    2.03 |        5 |         0 |        241 |        0 |       0 |
 sax.js        |   66.07 |      376 |        27 |        207 |        0 |       0 |
---------------|---------|----------|-----------|------------|----------|---------|
 INFO HtmlReporter Your report can be found at: reports/mutation/html/index.html
 INFO Stryker Done in 9 minutes 54 seconds.
```

**Comment by karfau** [comment]
I will wait for any reply before going further, I think the PR is already big enough.

**Comment by karfau** [comment]
To verify that nothing broke since forked, I did the following procedure
```
// assuming restore-test was checked out and npm i was run once before
git checkout $TAG
git checkout restore-tests -- test
//in test/**/*.vows.js point all imports to the correct location for this version
npx vows test/**/*.vows.js
```
Result:
**v0.1.27** (last version published by original author)
```
      ✗ text & < 
        »        
        actual expected 
         
        <div xmlns="http://www.w3.org/1999/xhtml"> ©&amp;nbsp&amp;copy</div> 
         // /run/media/karfau/hdd-data/dev/xmldom/node_modules/vows/lib/assert/macros.js:14 
  ✗ Broken » 71 honored ∙ 1 broken (3.567s) 
```
This is [this assertion](https://github.com/karfau/xmldom/blob/4c88be2d01660628861a64550ae3d6721eb9e897/test/html/normalize.vows.js#L13-L15), so I fixed it by adding back `\u00a0`.

**v0.1.28-not-published** (last tag pushed by original author)
```
      ✗ text & < 
        »        
        actual expected 
         
        <div xmlns="http://www.w3.org/1999/xhtml"> ©&amp;nbsp&amp;copy</div> 
         // /run/media/karfau/hdd-data/dev/xmldom/node_modules/vows/lib/assert/macros.js:14 
  ✗ Broken » 71 honored ∙ 1 broken (3.762s) 
```
Same assertion as above, so the regression was introduced by him.
Again fixed by adding back normal ` `.

**0.3.0** (first version with actual changes, no more `v` in the tag)
```
  ✓ OK » 72 honored (3.274s) 
```
since no code changes where done since that version: DONE :tada:

**Comment by karfau** [comment]
> My biggest criticism is that the change from fb6f516 shows way too much diff on GitHub. I would strongly favor keeping the formatting change in a separate PR and consider using something automatic such as eslint, "Standard JS", or Prettier.

Just to make sure we are talking about the same thing: 
When looking at that commit with github I don't see any changes in spaces or tabs or indentation:


so I checked the difference in my IDE:
image
So it's line separators... this change was of course unintended. But t's also a bit strange.
The [related git setting](https://help.github.com/en/github/using-git/configuring-git-to-handle-line-endings) is set to `input` since I'm on linux. I'm currently checking the details. It's possible that a mixture of line endings exists in the repo. Assuming I find something, do we generally agree that we should unify the line endings to LF in the repo as soon as possible?

Regarding splitting out into several PRs, that's fine. (I seem to have misunderstood your message in the issue as "stryker" being a requirement to fix/close the issue and assuming they should go into one PR.)

**Comment by brodybits** [comment]
> So it's line separators...

yup

> It's possible that a mixture of line endings exists in the repo.

I would not be surprised.

I generally use command-line tools together with `gitx`, didn't think of anything going on with the IDE.

I would actually favor that we restore the test coverage before dealing with the LF endings or any other formatting items.

In terms of Stryker, I could go either way at this point if the total changes do not prove excessive. I would still really like to get the `nbsp` fix into its own PR (and maybe an issue).

Another side point is that the name of `test/parse/test-doc-witespace.js` has a misspelling, it should probably be changed to: `test/parse/test-doc-whitespace.vows.js`.

**Comment by karfau** [comment]
Just thinking out loud here (and for referencing it later), this is my current plan:
0. file the requested issue and one for the line separator
1. on my machine for this project set `core.autocrlf false`
2. do a fresh checkout from upstream master
3. redo the minimal changes to get the `vows` test running and file the PR
4. after that PR landed, file a PR that fixes the line separators in the following 18 files
```
test/3rd-cases/o3xml.js
test/parse/namespace.js
test/parse/node.js
test/parse/big-file-performance.js
test/parse/simple.js
test/parse/parse-element.js
test/parse/locator.js
test/error/xml-error.js
test/error/error.js
test/html/normalize.js
test/dom/attr.js
test/dom/element.js
test/dom/level3.js
test/dom/clone.js
test/dom/index.js
test/test.js
test/index.js
__package__.js
```
5. unset `core.autocrlf false` (on my machine for this project)
6. continue to contribute :smile:

**Comment by karfau** [comment]
FYI: The checklist is complete, I will still keep the branch since there are some links to it by now and maybe also some other changes that we could pick from it. But nothing urgent.

**Pull request closed without merging**
