### PR TITLE
feat: implement Element.getElementsByClassName

### PR DESCRIPTION
**Pull request by censujiang**
- https://dom.spec.whatwg.org/#dom-element-getelementsbyclassname
- https://developer.mozilla.org/en-US/docs/Web/API/Element/getElementsByClassName

### CODE REVIEW

**Comment by censujiang** [comment]
This bug is fix for #582

**Comment by karfau** [comment]
Thank you for the effort.
Could you please translate the comments in the code to English?
It would also be very helpful if you can point to the specification that describes that Element and LiveNodeList have this method. The links should be part of the jsdoc comments and the PR description.

I would also consider this a PR that adds a `feat`ure, and not as a fix, since xmldom did not support this method on these Node types before.

Last but not least we will have to add test cases for all the newly supported code paths.

**Comment by censujiang** [comment]
> Thank you for the effort. Could you please translate the comments in the code to English? It would also be very helpful if you can point to the specification that describes that Element and LiveNodeList have this method. The links should be part of the jsdoc comments and the PR description.
> 
> I would also consider this a PR that adds a `feat`ure, and not as a fix, since xmldom did not support this method on these Node types before.
> 
> Last but not least we will have to add test cases for all the newly supported code paths.

I still don’t know why adding the function there can be successful. I just modified it based on observing the structure and general working principle of LiveNode, and after repeated testing on my project, I found that my approach was fine. I am better than you. I'm more curious why it works if I do this

**Comment by censujiang** [comment]
I will try my best to modify the relevant comments in the code, but I do not guarantee that this will comply with the specifications of this project.

**Comment by censujiang** [comment]
I have modified the relevant comment operations, but because I cannot write test code, I cannot submit the test code to you.

**Comment by karfau** [comment]
Can you help me to understand why you are can not add tests?

**Comment by censujiang** [comment]
> Can you help me to understand why you can not add tests?

Because I have never written test code in my life...😥

**Comment by karfau** [comment]
Ok, but do you want to learn it?
Not that this repository is a simple one to get onboarded to,
so maybe you want to get started with testing by folliwing a tutorial like this one to get a general understanding:
https://dev.to/dsasse07/a-beginner-s-guide-to-unit-testing-with-jest-45cc

There are plenty of existing tests in this repository to look at and of course you don't need to configure jest in this repo, you need to run `npm ci` once to install the dependencies if you havent done it already, and run `npm test` to run all tests once or `npm test -- --watch` to rerun the ones related to your changes whenever you save a file.

The tests ones for `Document.getElementsByClassName`:
https://github.com/xmldom/xmldom/blob/14e96bc05c253f76e46fb21f35e9df3d844b7e9f/test/dom/document.test.js#L46
should be a good starting point for what needs to be added to the tests for `Element`s:
https://github.com/xmldom/xmldom/blob/14e96bc05c253f76e46fb21f35e9df3d844b7e9f/test/dom/element.test.js#L126
With the difference that you need to call the method on an element node instead of on  the documentElement.

Do you want to give it a try?

**Comment by censujiang** [comment]
I tried to write a little test code and it currently works

**Comment by karfau** [comment]
That is a great starting point.

When I'm back at my computer next week I will have a closer look at your implementation an potentially mising tests or possible refactoring in the context of this change.
I have not found any spec mentioning that LiveNodeList should implement this method.

If you have a resource that shows this, please provide a link.

**Comment by censujiang** [comment]
> That is a great starting point.
> 
> When I'm back at my computer next week I will have a closer look at your implementation an potentially mising tests or possible refactoring in the context of this change. I have not found any spec mentioning that LiveNodeList should implement this method.
> 
> If you have a resource that shows this, please provide a link.

okay, Thank you!

**Comment by karfau** [comment]
@censujiang thank you for your work, I finally found time to revisit the work you did.
Since I would have needed to tweak the PR a bit on your fork I decided to instead create a new PR #722 to implement the feature, so I'm closing this one.

**Comment by censujiang** [comment]
ok, thank you!

**Pull request closed without merging**
